/*===============================================
    supplement_setup.sql
    - 기존 DB에 누락된 오브젝트 추가 (멱등성 보장)
    - 기존 테이블/데이터는 삭제하지 않음
    - FFINAL1 계정으로 실행
    - 기준: 260615 DDL 익스포트 + 이후 추가분

    실행 전 SYS 계정으로 한 번만 실행:
      ALTER SESSION SET "_ORACLE_SCRIPT"=TRUE;
      GRANT EXECUTE ON DBMS_CRYPTO TO FFINAL1;
      GRANT EXECUTE ON UTL_HTTP TO FFINAL1;
      GRANT EXECUTE ON DBMS_SCHEDULER TO FFINAL1;
      GRANT EXECUTE ON DBMS_LOCK TO FFINAL1;
===============================================*/


/*==========================================
  [1] 테이블 생성 (없을 경우에만)
==========================================*/

BEGIN EXECUTE IMMEDIATE '
    CREATE TABLE ADMIN_ACCOUNT (
        ADMIN_NO  NUMBER,
        ID        VARCHAR2(100),
        PW        VARCHAR2(500)
    )
'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

BEGIN EXECUTE IMMEDIATE '
    CREATE TABLE MEMBER_MASTER (
        MEMBER_NO  NUMBER,
        CREATE_DT  DATE DEFAULT SYSDATE
    )
'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

BEGIN EXECUTE IMMEDIATE '
    CREATE TABLE MEMBER_ACTIVE (
        MEMBER_NO  NUMBER,
        NAME       VARCHAR2(50),
        NICKNAME   VARCHAR2(50),
        ID         VARCHAR2(50),
        PW         VARCHAR2(500),
        EMAIL      VARCHAR2(100),
        PHONE_NO   VARCHAR2(500)
    )
'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

BEGIN EXECUTE IMMEDIATE '
    CREATE TABLE MEMBER_LEAVE (
        MEMBER_NO  NUMBER,
        NAME       VARCHAR2(50),
        NICKNAME   VARCHAR2(50),
        ID         VARCHAR2(50),
        PW         VARCHAR2(500),
        EMAIL      VARCHAR2(100),
        PHONE_NO   VARCHAR2(500),
        LEAVE_DT   DATE DEFAULT SYSDATE
    )
'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

BEGIN EXECUTE IMMEDIATE '
    CREATE TABLE MEMBER_SANCTION (
        SANCTION_NO    NUMBER,
        MEMBER_NO      NUMBER,
        LEVEL_DAYS     NUMBER,
        REASON         VARCHAR2(100),
        COMMENT        VARCHAR2(500),
        ADMIN_NO       NUMBER,
        SANCTION_DT    DATE DEFAULT SYSDATE,
        SANCTION_UNTIL DATE
    )
'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

BEGIN EXECUTE IMMEDIATE '
    CREATE TABLE CONTENTCATEGORY (
        CONTENTTYPEID  VARCHAR2(1000),
        CONTENTDIV     VARCHAR2(100)
    )
'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

BEGIN EXECUTE IMMEDIATE '
    CREATE TABLE CONTENT (
        CONTENTID      NUMBER,
        TITLE          VARCHAR2(500),
        ADDR1          VARCHAR2(1000),
        ADDR2          VARCHAR2(1000),
        CONTENTTYPEID  VARCHAR2(1000),
        CREATEDTIME    VARCHAR2(14),
        MAPX           NUMBER(20,15),
        MAPY           NUMBER(20,15),
        MODIFIEDTIME   VARCHAR2(14),
        APIID          VARCHAR2(100),
        FIRSTIMAGE     VARCHAR2(1000),
        FIRSTIMAGE2    VARCHAR2(1000)
    )
'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

-- CONTENT.APIID UNIQUE 제약
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE CONTENT ADD CONSTRAINT UK_CONTENT_APIID UNIQUE (APIID)';
EXCEPTION WHEN OTHERS THEN NULL; END;
/

BEGIN EXECUTE IMMEDIATE '
    CREATE TABLE CONTENTEVENT (
        CONTENTID       NUMBER,
        EVENTSTARTDATE  VARCHAR2(8),
        EVENTENDDATE    VARCHAR2(8)
    )
'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

-- CONTENTIMAGE: IDENTITY 컬럼 + CPYRHTDIVCD + SERIALNUM (DDL 익스포트 기준)
BEGIN EXECUTE IMMEDIATE '
    CREATE TABLE CONTENTIMAGE (
        CONTENTIMAGEID  NUMBER GENERATED BY DEFAULT AS IDENTITY,
        APIID           VARCHAR2(100),
        ORIGINIMGURL    VARCHAR2(1000),
        IMGNAME         VARCHAR2(500),
        CPYRHTDIVCD     VARCHAR2(100),
        SERIALNUM       VARCHAR2(500)
    )
'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

-- CONTENTIMAGE_SYNC: API 동기화 상태 추적 (S:성공, E:실패, N:미처리)
BEGIN EXECUTE IMMEDIATE '
    CREATE TABLE CONTENTIMAGE_SYNC (
        APIID      VARCHAR2(100),
        SYNC_DATE  DATE DEFAULT SYSDATE,
        STATUS     VARCHAR2(10) DEFAULT ''S''
    )
'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

-- IDX_CONTENTIMAGE_APIID_SERIAL: CONTENTIMAGE 검색 인덱스
BEGIN EXECUTE IMMEDIATE 'CREATE INDEX IDX_CONTENTIMAGE_APIID_SERIAL ON CONTENTIMAGE (APIID, SERIALNUM)';
EXCEPTION WHEN OTHERS THEN NULL; END;
/

BEGIN EXECUTE IMMEDIATE '
    CREATE TABLE CONTENT_REVIEW (
        CONTENT_REVIEW_NO  NUMBER,
        MEMBER_NO          NUMBER,
        CONTENTID          NUMBER,
        CREATE_DT          DATE DEFAULT SYSDATE,
        REVIEW_COMMENT     VARCHAR2(2000),
        RATING             NUMBER(1,0),
        BLIND_YN           CHAR(1) DEFAULT ''N''
    )
'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

-- REVIEW_REPORT_TYPE: REPORT_TYPE_CD 는 VARCHAR2(10) (DDL 익스포트 기준)
BEGIN EXECUTE IMMEDIATE '
    CREATE TABLE REVIEW_REPORT_TYPE (
        REPORT_TYPE_CD  VARCHAR2(10),
        REPORT_TYPE_NM  VARCHAR2(100)
    )
'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

-- REVIEW_REPORT: REPORT_TYPE_CD 는 VARCHAR2(10) FK
BEGIN EXECUTE IMMEDIATE '
    CREATE TABLE REVIEW_REPORT (
        REVIEW_REPORT_NO    NUMBER,
        REPORTER_MEMBER_NO  NUMBER,
        CONTENT_REVIEW_NO   NUMBER,
        REPORT_TYPE_CD      VARCHAR2(10),
        REPORT_DT           DATE DEFAULT SYSDATE,
        REPORT_COMMENT      VARCHAR2(2000),
        PROCESS_YN          CHAR(1) DEFAULT ''N''
    )
'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

BEGIN EXECUTE IMMEDIATE '
    CREATE TABLE MEMBER_BOOKMARK (
        BOOKMARK_NO  NUMBER,
        MEMBER_NO    NUMBER,
        CONTENTID    NUMBER,
        CREATE_DT    DATE DEFAULT SYSDATE
    )
'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

BEGIN EXECUTE IMMEDIATE '
    CREATE TABLE NOTICE (
        NOTICE_NO       NUMBER,
        ADMIN_NO        NUMBER,
        CREATE_DT       DATE DEFAULT SYSDATE,
        NOTICE_TITLE    VARCHAR2(200),
        NOTICE_CONTENT  VARCHAR2(2000),
        VIEW_CNT        NUMBER DEFAULT 0
    )
'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

BEGIN EXECUTE IMMEDIATE '
    CREATE TABLE FAQ_TYPE (
        FAQ_TYPE_CD  VARCHAR2(10),
        FAQ_TYPE_NM  VARCHAR2(100)
    )
'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

BEGIN EXECUTE IMMEDIATE '
    CREATE TABLE FAQ (
        FAQ_NO        NUMBER,
        FAQ_TYPE_CD   VARCHAR2(10),
        ADMIN_NO      NUMBER,
        CREATE_DT     DATE DEFAULT SYSDATE,
        FAQ_QUESTION  VARCHAR2(200),
        FAQ_ANSWER    VARCHAR2(2000)
    )
'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

BEGIN EXECUTE IMMEDIATE '
    CREATE TABLE QNA_TYPE (
        QNA_TYPE_CD  VARCHAR2(10),
        QNA_TYPE_NM  VARCHAR2(100)
    )
'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

BEGIN EXECUTE IMMEDIATE '
    CREATE TABLE QNA_QUESTION (
        QNA_REQ_NO   NUMBER,
        MEMBER_NO    NUMBER,
        QNA_TYPE_CD  VARCHAR2(10),
        CREATE_DT    DATE DEFAULT SYSDATE,
        QNA_TITLE    VARCHAR2(200),
        QNA_CONTENT  VARCHAR2(2000),
        STATUS_CD    VARCHAR2(10) DEFAULT ''ST001''
    )
'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

BEGIN EXECUTE IMMEDIATE '
    CREATE TABLE QNA_ANSWER (
        QNA_ANS_NO   NUMBER,
        QNA_REQ_NO   NUMBER,
        ADMIN_NO     NUMBER,
        CREATE_DT    DATE DEFAULT SYSDATE,
        ANS_CONTENT  VARCHAR2(2000)
    )
'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

BEGIN EXECUTE IMMEDIATE '
    CREATE TABLE PENALTY_LEVEL (
        PENALTY_LV_CD   VARCHAR2(10),
        SUSPENSION_DAYS NUMBER,
        PENALTY_REA_NM  VARCHAR2(100)
    )
'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

BEGIN EXECUTE IMMEDIATE '
    CREATE TABLE PENALTY_HISTORY (
        PENALTY_HIST_NO    NUMBER,
        ADMIN_NO           NUMBER,
        MEMBER_NO          NUMBER,
        PENALTY_LV_CD      VARCHAR2(10),
        CONTENT_REVIEW_NO  NUMBER,
        CREATE_DT          DATE DEFAULT SYSDATE,
        PENALTY_MEMO       VARCHAR2(2000)
    )
'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

-- SYSTEM_CONFIG: API 키 등 설정값 저장 (프로시저에서 참조)
BEGIN EXECUTE IMMEDIATE '
    CREATE TABLE SYSTEM_CONFIG (
        KEY_NAME    VARCHAR2(100),
        KEY_VALUE   VARCHAR2(1000),
        DESCRIPTION VARCHAR2(500)
    )
'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

-- TEMP_API_CONTENT: API 동기화 임시 테이블 (세션 종료 시 보존)
BEGIN EXECUTE IMMEDIATE '
    CREATE GLOBAL TEMPORARY TABLE TEMP_API_CONTENT (
        API_ID          VARCHAR2(100),
        TITLE           VARCHAR2(500),
        ADDR1           VARCHAR2(1000),
        ADDR2           VARCHAR2(1000),
        CONTENTTYPEID   VARCHAR2(1000),
        CREATEDTIME     VARCHAR2(14),
        MAPX            NUMBER,
        MAPY            NUMBER,
        MODIFIEDTIME    VARCHAR2(14),
        FIRSTIMAGE      VARCHAR2(1000),
        FIRSTIMAGE2     VARCHAR2(1000),
        EVENTSTARTDATE  VARCHAR2(8),
        EVENTENDDATE    VARCHAR2(8),
        NEW_CONTENTID   NUMBER
    ) ON COMMIT PRESERVE ROWS
'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

BEGIN EXECUTE IMMEDIATE '
    CREATE TABLE TRAVEL_THEME (
        TRAVEL_THEME_CD  VARCHAR2(20),
        TRAVEL_THEME_NM  VARCHAR2(100)
    )
'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

BEGIN EXECUTE IMMEDIATE '
    CREATE TABLE TRAVEL_PLAN (
        TRAVEL_PLAN_NO      NUMBER,
        HOST_MEMBER_NO      NUMBER,
        TRAVEL_NAME         VARCHAR2(200),
        TRAVEL_THEME_CD     VARCHAR2(20),
        TRAVEL_START_DT     DATE,
        TRAVEL_END_DT       DATE,
        OUTLINE             VARCHAR2(1000),
        ROOT_TRAVEL_PLAN_NO NUMBER,
        REVISION_DT         DATE DEFAULT SYSDATE
    )
'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

BEGIN EXECUTE IMMEDIATE '
    CREATE TABLE ACTION_TYPE (
        ACTION_TYPE_CD  VARCHAR2(6),
        ACTION_TYPE_NM  VARCHAR2(20)
    )
'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

BEGIN EXECUTE IMMEDIATE '
    CREATE TABLE PLAN_GUEST (
        PLAN_GUEST_NO   NUMBER,
        TRAVEL_PLAN_NO  NUMBER,
        MEMBER_NO       NUMBER,
        CREATE_DT       DATE DEFAULT SYSDATE
    )
'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

BEGIN EXECUTE IMMEDIATE '
    CREATE TABLE PLAN_GUEST_LEAVE_TYPE (
        GUEST_LEAVE_CD  VARCHAR2(10),
        GUEST_LEAVE_NM  VARCHAR2(100)
    )
'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

BEGIN EXECUTE IMMEDIATE '
    CREATE TABLE PLAN_GUEST_LEAVE (
        PLAN_GUEST_NO  NUMBER,
        LEAVE_DATE     DATE DEFAULT SYSDATE,
        LEAVE_TYPE     VARCHAR2(10)
    )
'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

BEGIN EXECUTE IMMEDIATE '
    CREATE TABLE PLAN_HOST_HIST (
        PLAN_HOST_HIST_NO  NUMBER,
        TRAVEL_PLAN_NO     NUMBER,
        PLAN_GUEST_NO      NUMBER,
        CREATE_DT          DATE DEFAULT SYSDATE
    )
'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

BEGIN EXECUTE IMMEDIATE '
    CREATE TABLE TRAVEL_ITINERARY (
        TRAVEL_ITINERARY_NO  NUMBER,
        TRAVEL_PLAN_NO       NUMBER,
        CONTENT_NO           NUMBER,
        ITINERARY_NM         VARCHAR2(200),
        ITINERARY_DT         DATE,
        ITINERARY_TIME       VARCHAR2(10),
        ITINERARY_MEMO       VARCHAR2(2000)
    )
'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

BEGIN EXECUTE IMMEDIATE '
    CREATE TABLE ITINERARY_EXPENSE_TYPE (
        EXPENSE_TYPE_CD  VARCHAR2(10),
        EXPENSE_TYPE_NM  VARCHAR2(100)
    )
'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

BEGIN EXECUTE IMMEDIATE '
    CREATE TABLE ITINERARY_EXPENSE (
        ITINERARY_EXPENSE_NO    NUMBER,
        TRAVEL_ITINERARY_NO     NUMBER,
        ITINERARY_EXPENSE_TYPE  VARCHAR2(10),
        EXPENSE_AMT             NUMBER,
        CREATE_DT               DATE DEFAULT SYSDATE
    )
'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

-- TRAVEL_ITINERARY_HIST: DDL 익스포트 기준 실제 스키마
BEGIN EXECUTE IMMEDIATE '
    CREATE TABLE TRAVEL_ITINERARY_HIST (
        ITINERARY_HIST_NO    NUMBER,
        TRAVEL_ITINERARY_NO  NUMBER,
        PLAN_GUEST_NO        NUMBER,
        CONTENT_NO           NUMBER,
        ACTION_TYPE_CD       VARCHAR2(6),
        EDIT_DT              DATE DEFAULT SYSDATE,
        ITINERARY_NM         VARCHAR2(200),
        ITINERARY_DT         DATE,
        ITINERARY_TIME       VARCHAR2(10),
        ITINERARY_MEMO       VARCHAR2(2000),
        ESTIMATED_EXPENSE    NUMBER,
        ACTUAL_EXPENSE       NUMBER
    )
'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

-- TRAVEL_ITINERARY_DEL: DDL 익스포트 기준 실제 스키마 (ITINERARY_DEL_NO 가 PK)
BEGIN EXECUTE IMMEDIATE '
    CREATE TABLE TRAVEL_ITINERARY_DEL (
        ITINERARY_DEL_NO     NUMBER,
        TRAVEL_ITINERARY_NO  NUMBER,
        DEL_DT               DATE DEFAULT SYSDATE,
        DELETER_GUEST_NO     NUMBER
    )
'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

-- TRAVEL_INVITATION: 초대코드 테이블 (DDL 익스포트 기준)
BEGIN EXECUTE IMMEDIATE '
    CREATE TABLE TRAVEL_INVITATION (
        TRAVEL_INVITATION_NO  NUMBER,
        CREATE_DT             DATE DEFAULT SYSDATE,
        INVITE_CODE           CHAR(16),
        TRAVEL_PLAN_NO        NUMBER
    )
'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

-- PLAN_CHECKLIST: 여행 체크리스트 (post-June 15 추가)
BEGIN EXECUTE IMMEDIATE '
    CREATE TABLE PLAN_CHECKLIST (
        CHECKLIST_NO    NUMBER,
        TRAVEL_PLAN_NO  NUMBER,
        CONTENT         VARCHAR2(200),
        IS_CHECKED      NUMBER(1) DEFAULT 0,
        CREATE_DT       DATE DEFAULT SYSDATE
    )
'; EXCEPTION WHEN OTHERS THEN NULL; END;
/


/*==========================================
  [2] 컬럼 추가 (없을 경우에만)
==========================================*/

-- CONTENT_REVIEW: 블라인드 처리 컬럼
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE CONTENT_REVIEW ADD BLIND_YN CHAR(1) DEFAULT ''N''';
EXCEPTION WHEN OTHERS THEN NULL; END;
/

-- TRAVEL_INVITATION: 직접 초대 지원 컬럼
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE TRAVEL_INVITATION ADD INVITEE_MEMBER_NO NUMBER';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE TRAVEL_INVITATION ADD INVITE_STATUS VARCHAR2(10)';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE TRAVEL_INVITATION MODIFY INVITE_CODE NULL';
EXCEPTION WHEN OTHERS THEN NULL; END;
/

-- PLAN_GUEST: 수정 권한
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE PLAN_GUEST ADD CAN_EDIT NUMBER(1) DEFAULT 1';
EXCEPTION WHEN OTHERS THEN NULL; END;
/

-- TRAVEL_PLAN: 공개 여부
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE TRAVEL_PLAN ADD IS_PUBLIC NUMBER(1) DEFAULT 0';
EXCEPTION WHEN OTHERS THEN NULL; END;
/

-- ITINERARY_EXPENSE: 예상 비용 / 결제 방법 / 메모
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE ITINERARY_EXPENSE ADD ESTIMATED_AMT NUMBER DEFAULT 0';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE ITINERARY_EXPENSE ADD PAYMENT_METHOD VARCHAR2(50)';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE ITINERARY_EXPENSE ADD EXPENSE_MEMO VARCHAR2(200)';
EXCEPTION WHEN OTHERS THEN NULL; END;
/

-- TRAVEL_ITINERARY_HIST: 삭제된 일정도 planNo 기준으로 직접 조회 가능하게
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE TRAVEL_ITINERARY_HIST ADD TRAVEL_PLAN_NO NUMBER';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
-- FK_HIST_ITINERARY 제거 (일정 삭제 후에도 이력 보존)
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE TRAVEL_ITINERARY_HIST DROP CONSTRAINT FK_HIST_ITINERARY';
EXCEPTION WHEN OTHERS THEN NULL; END;
/


/*==========================================
  [3] 시퀀스 생성 (없을 경우에만)
==========================================*/

BEGIN EXECUTE IMMEDIATE 'CREATE SEQUENCE ADMIN_ACCOUNT_SEQ        START WITH 1 INCREMENT BY 1 NOMAXVALUE NOCYCLE NOCACHE';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'CREATE SEQUENCE MEMBER_MASTER_SEQ         START WITH 1 INCREMENT BY 1 NOMAXVALUE NOCYCLE NOCACHE';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'CREATE SEQUENCE MEMBER_SANCTION_SEQ       START WITH 1 INCREMENT BY 1 NOMAXVALUE NOCYCLE NOCACHE';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'CREATE SEQUENCE MEMBER_BOOKMARK_SEQ       START WITH 1 INCREMENT BY 1 NOMAXVALUE NOCYCLE NOCACHE';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'CREATE SEQUENCE NOTICE_SEQ                START WITH 1 INCREMENT BY 1 NOMAXVALUE NOCYCLE NOCACHE';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'CREATE SEQUENCE FAQ_SEQ                   START WITH 1 INCREMENT BY 1 NOMAXVALUE NOCYCLE NOCACHE';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'CREATE SEQUENCE QNA_QUESTION_SEQ          START WITH 1 INCREMENT BY 1 NOMAXVALUE NOCYCLE NOCACHE';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'CREATE SEQUENCE QNA_ANSWER_SEQ            START WITH 1 INCREMENT BY 1 NOMAXVALUE NOCYCLE NOCACHE';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'CREATE SEQUENCE QNA_TYPE_SEQ              START WITH 1 INCREMENT BY 1 NOMAXVALUE NOCYCLE NOCACHE';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'CREATE SEQUENCE SEQ_CONTENTID             START WITH 1 INCREMENT BY 1 NOMAXVALUE NOCYCLE NOCACHE';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
-- SEQ_CONTENT: P_CONTENT_API_UPSERT 프로시저에서 사용
BEGIN EXECUTE IMMEDIATE 'CREATE SEQUENCE SEQ_CONTENT               START WITH 1 INCREMENT BY 1 NOMAXVALUE NOCYCLE NOCACHE';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'CREATE SEQUENCE CONTENT_REVIEW_SEQ        START WITH 1 INCREMENT BY 1 NOMAXVALUE NOCYCLE NOCACHE';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'CREATE SEQUENCE REVIEW_REPORT_SEQ         START WITH 1 INCREMENT BY 1 NOMAXVALUE NOCYCLE NOCACHE';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'CREATE SEQUENCE PENALTY_HISTORY_SEQ       START WITH 1 INCREMENT BY 1 NOMAXVALUE NOCYCLE NOCACHE';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'CREATE SEQUENCE TRAVEL_PLAN_SEQ           START WITH 1 INCREMENT BY 1 NOMAXVALUE NOCYCLE NOCACHE';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'CREATE SEQUENCE TRAVEL_ITINERARY_SEQ      START WITH 1 INCREMENT BY 1 NOMAXVALUE NOCYCLE NOCACHE';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'CREATE SEQUENCE TRAVEL_ITINERARY_HIST_SEQ START WITH 1 INCREMENT BY 1 NOMAXVALUE NOCYCLE NOCACHE';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'CREATE SEQUENCE TRAVEL_ITINERARY_DEL_SEQ  START WITH 1 INCREMENT BY 1 NOMAXVALUE NOCYCLE NOCACHE';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'CREATE SEQUENCE TRAVEL_INVITATION_SEQ     START WITH 1 INCREMENT BY 1 NOMAXVALUE NOCYCLE NOCACHE';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'CREATE SEQUENCE PLAN_GUEST_SEQ            START WITH 1 INCREMENT BY 1 NOMAXVALUE NOCYCLE NOCACHE';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'CREATE SEQUENCE PLAN_HOST_HIST_SEQ        START WITH 1 INCREMENT BY 1 NOMAXVALUE NOCYCLE NOCACHE';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'CREATE SEQUENCE ITINERARY_EXPENSE_SEQ     START WITH 1 INCREMENT BY 1 NOMAXVALUE NOCYCLE NOCACHE';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'CREATE SEQUENCE PLAN_CHECKLIST_SEQ        START WITH 1 INCREMENT BY 1 NOMAXVALUE NOCYCLE NOCACHE';
EXCEPTION WHEN OTHERS THEN NULL; END;
/


/*==========================================
  [4] CRYPTPACK 패키지 (AES256 암호화)
      사전 필요: GRANT EXECUTE ON DBMS_CRYPTO TO FFINAL1;
==========================================*/

CREATE OR REPLACE PACKAGE CRYPTPACK
AS
    FUNCTION ENCRYPT(STR VARCHAR2, HASH VARCHAR2) RETURN VARCHAR2;
    FUNCTION DECRYPT(XCRYPT VARCHAR2, HASH VARCHAR2) RETURN VARCHAR2;
END CRYPTPACK;
/

CREATE OR REPLACE PACKAGE BODY CRYPTPACK
AS
    V_TYP CONSTANT PLS_INTEGER := DBMS_CRYPTO.ENCRYPT_AES256
                                + DBMS_CRYPTO.CHAIN_CBC
                                + DBMS_CRYPTO.PAD_PKCS5;

    FUNCTION ENCRYPT(STR VARCHAR2, HASH VARCHAR2)
    RETURN VARCHAR2
    IS
        V_RAW       RAW(2000);
        V_KEY_RAW   RAW(32);
        V_ENCRYPTED RAW(2000);
    BEGIN
        V_RAW       := UTL_I18N.STRING_TO_RAW(STR, 'AL32UTF8');
        V_KEY_RAW   := UTL_RAW.CAST_TO_RAW(RPAD(HASH, 32, '#'));
        V_ENCRYPTED := DBMS_CRYPTO.ENCRYPT(
            SRC => V_RAW,
            TYP => V_TYP,
            KEY => V_KEY_RAW
        );
        RETURN RAWTOHEX(V_ENCRYPTED);
    END;

    FUNCTION DECRYPT(XCRYPT VARCHAR2, HASH VARCHAR2)
    RETURN VARCHAR2
    IS
        V_DECRYPTED_RAW RAW(2000);
        V_KEY_RAW       RAW(32);
    BEGIN
        V_KEY_RAW := UTL_RAW.CAST_TO_RAW(RPAD(HASH, 32, '#'));
        V_DECRYPTED_RAW := DBMS_CRYPTO.DECRYPT(
            SRC => HEXTORAW(XCRYPT),
            TYP => V_TYP,
            KEY => V_KEY_RAW
        );
        RETURN UTL_I18N.RAW_TO_CHAR(V_DECRYPTED_RAW, 'AL32UTF8');
    EXCEPTION
        WHEN OTHERS THEN RETURN 'DECRYPT_ERROR';
    END;

END CRYPTPACK;
/


/*==========================================
  [5] API 동기화 프로시저
      사전 필요: GRANT EXECUTE ON UTL_HTTP TO FFINAL1;
                GRANT EXECUTE ON DBMS_LOCK TO FFINAL1;
==========================================*/

-- 컨텐츠 동기화 (CONTENT + CONTENTEVENT UPSERT)
CREATE OR REPLACE PROCEDURE P_CONTENT_API_UPSERT
IS
    V_REQ          UTL_HTTP.req;
    V_RESP         UTL_HTTP.resp;
    buffer         VARCHAR2(32767);
    V_RESPONSE     CLOB;
    V_URL          VARCHAR2(2000);

    V_PAGE_NO      NUMBER;
    V_NUM_OF_ROWS  NUMBER := 100;
    V_TOTAL_COUNT  NUMBER := 0;
    V_MAX_PAGE     NUMBER;

    V_AREA_CODE      VARCHAR2(10);
    V_API_KEY        VARCHAR2(200);
    V_CONTENTTYPEID  VARCHAR2(1000);
    V_EVENTSTARTDATE VARCHAR2(8);
BEGIN
    V_AREA_CODE      := '1';
    V_EVENTSTARTDATE := '20000101';
    V_API_KEY        := 'YOUR_API_KEY_HERE';

    FOR cat IN (SELECT CONTENTTYPEID FROM CONTENTCATEGORY ORDER BY CONTENTTYPEID) LOOP

        V_CONTENTTYPEID := cat.CONTENTTYPEID;
        V_PAGE_NO       := 1;
        V_MAX_PAGE      := 1;

        BEGIN
            WHILE V_PAGE_NO <= V_MAX_PAGE LOOP

                IF V_CONTENTTYPEID = '15' THEN
                    V_URL := 'http://apis.data.go.kr/B551011/KorService2/searchFestival2';
                ELSE
                    V_URL := 'http://apis.data.go.kr/B551011/KorService2/areaBasedList2';
                END IF;

                V_URL := V_URL
                    || '?numOfRows=' || V_NUM_OF_ROWS
                    || '&pageNo='    || V_PAGE_NO
                    || '&MobileOS=WEB'
                    || '&MobileApp=TravelMate'
                    || '&areaCode='  || V_AREA_CODE
                    || '&_type=json'
                    || '&serviceKey=' || V_API_KEY;

                IF V_CONTENTTYPEID = '15' THEN
                    V_URL := V_URL || '&eventStartDate=' || V_EVENTSTARTDATE;
                ELSE
                    V_URL := V_URL || '&contentTypeId=' || V_CONTENTTYPEID;
                END IF;

                BEGIN
                    DBMS_LOB.createtemporary(V_RESPONSE, TRUE);

                    V_REQ := UTL_HTTP.begin_request(V_URL);
                    UTL_HTTP.SET_HEADER(V_REQ, 'Content-Type', 'application/json; charset=UTF-8');
                    UTL_HTTP.SET_BODY_CHARSET(V_REQ, 'UTF-8');
                    V_RESP := UTL_HTTP.get_response(V_REQ);
                    UTL_HTTP.SET_BODY_CHARSET(V_RESP, 'UTF-8');

                    BEGIN
                        LOOP
                            UTL_HTTP.read_text(V_RESP, buffer, 32767);
                            DBMS_LOB.writeappend(V_RESPONSE, LENGTH(buffer), buffer);
                        END LOOP;
                    EXCEPTION
                        WHEN UTL_HTTP.end_of_body THEN NULL;
                    END;
                    UTL_HTTP.end_response(V_RESP);

                    V_TOTAL_COUNT := TO_NUMBER(JSON_VALUE(V_RESPONSE, '$.response.body.totalCount'));

                    IF V_PAGE_NO = 1 THEN
                        IF V_TOTAL_COUNT > 0 THEN
                            V_MAX_PAGE := CEIL(V_TOTAL_COUNT / V_NUM_OF_ROWS);
                        ELSE
                            V_MAX_PAGE := 0;
                        END IF;
                        DBMS_OUTPUT.PUT_LINE('== 컨텐츠타입 : ' || V_CONTENTTYPEID || ' ===');
                        DBMS_OUTPUT.PUT_LINE('총 데이터 수 : ' || V_TOTAL_COUNT || '건, 총 페이지 수: ' || V_MAX_PAGE || '개');
                    END IF;

                    IF V_TOTAL_COUNT > 0 THEN
                        FOR r IN (
                            SELECT *
                            FROM JSON_TABLE(V_RESPONSE, '$.response.body.items.item[*]'
                                    COLUMNS (
                                        title          VARCHAR2(500)  PATH '$.title',
                                        addr1          VARCHAR2(1000) PATH '$.addr1',
                                        addr2          VARCHAR2(1000) PATH '$.addr2',
                                        contenttypeid  VARCHAR2(1000) PATH '$.contenttypeid',
                                        createdtime    VARCHAR2(14)   PATH '$.createdtime',
                                        mapx           NUMBER         PATH '$.mapx',
                                        mapy           NUMBER         PATH '$.mapy',
                                        modifiedtime   VARCHAR2(14)   PATH '$.modifiedtime',
                                        api_id         VARCHAR2(100)  PATH '$.contentid',
                                        firstimage     VARCHAR2(1000) PATH '$.firstimage',
                                        firstimage2    VARCHAR2(1000) PATH '$.firstimage2',
                                        eventstartdate VARCHAR2(8)    PATH '$.eventstartdate',
                                        eventenddate   VARCHAR2(8)    PATH '$.eventenddate'
                                    )
                                 )
                        ) LOOP
                            DECLARE
                                V_CURRENT_CONTENTID NUMBER;
                                V_IS_CHANGED        CHAR(1) := 'N';
                            BEGIN
                                MERGE INTO CONTENT t
                                USING DUAL
                                ON (t.APIID = r.api_id)
                                WHEN MATCHED THEN
                                    UPDATE SET
                                        t.TITLE         = r.title,
                                        t.ADDR1         = r.addr1,
                                        t.ADDR2         = r.addr2,
                                        t.CONTENTTYPEID = r.contenttypeid,
                                        t.CREATEDTIME   = r.createdtime,
                                        t.MAPX          = r.mapx,
                                        t.MAPY          = r.mapy,
                                        t.MODIFIEDTIME  = r.modifiedtime,
                                        t.FIRSTIMAGE    = r.firstimage,
                                        t.FIRSTIMAGE2   = r.firstimage2
                                    WHERE t.MODIFIEDTIME <> r.modifiedtime
                                WHEN NOT MATCHED THEN
                                    INSERT (CONTENTID, TITLE, ADDR1, ADDR2, CONTENTTYPEID,
                                            CREATEDTIME, MAPX, MAPY, MODIFIEDTIME, APIID,
                                            FIRSTIMAGE, FIRSTIMAGE2)
                                    VALUES (SEQ_CONTENT.NEXTVAL, r.title, r.addr1, r.addr2,
                                            r.contenttypeid, r.createdtime, r.mapx, r.mapy,
                                            r.modifiedtime, r.api_id, r.firstimage, r.firstimage2);

                                IF SQL%ROWCOUNT > 0 THEN V_IS_CHANGED := 'Y'; END IF;

                                SELECT CONTENTID INTO V_CURRENT_CONTENTID
                                FROM CONTENT WHERE APIID = r.api_id;

                                IF V_CONTENTTYPEID = '15' THEN
                                    MERGE INTO CONTENTEVENT e
                                    USING DUAL
                                    ON (e.CONTENTID = V_CURRENT_CONTENTID)
                                    WHEN MATCHED THEN
                                        UPDATE SET
                                            e.EVENTSTARTDATE = r.eventstartdate,
                                            e.EVENTENDDATE   = r.eventenddate
                                        WHERE V_IS_CHANGED = 'Y'
                                    WHEN NOT MATCHED THEN
                                        INSERT (CONTENTID, EVENTSTARTDATE, EVENTENDDATE)
                                        VALUES (V_CURRENT_CONTENTID, r.eventstartdate, r.eventenddate);
                                END IF;
                            END;
                        END LOOP;
                    END IF;

                    COMMIT;
                    DBMS_OUTPUT.PUT_LINE('카테고리[' || V_CONTENTTYPEID || '] 페이지: '
                                         || V_PAGE_NO || ' / ' || V_MAX_PAGE || ' 완료');

                EXCEPTION
                    WHEN OTHERS THEN
                        ROLLBACK;
                        DBMS_OUTPUT.PUT_LINE('[에러] 카테고리 ' || V_CONTENTTYPEID
                                             || ' / 페이지 ' || V_PAGE_NO || ': ' || SQLERRM);
                END;

                IF DBMS_LOB.istemporary(V_RESPONSE) = 1 THEN
                    DBMS_LOB.freetemporary(V_RESPONSE);
                END IF;
                V_PAGE_NO := V_PAGE_NO + 1;

            END LOOP;

        EXCEPTION
            WHEN OTHERS THEN
                DBMS_OUTPUT.PUT_LINE('카테고리 [' || V_CONTENTTYPEID || '] 치명적 에러: ' || SQLERRM);
        END;

    END LOOP;

    DBMS_OUTPUT.PUT_LINE('=== P_CONTENT_API_UPSERT 완료 ===');

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        IF DBMS_LOB.istemporary(V_RESPONSE) = 1 THEN DBMS_LOB.freetemporary(V_RESPONSE); END IF;
        DBMS_OUTPUT.PUT_LINE('ERR=' || SQLCODE || ' / ' || SQLERRM);
END P_CONTENT_API_UPSERT;
/


-- 컨텐츠 이미지 동기화 (CONTENTIMAGE UPSERT, 429/할당량 초과 대응)
-- API 키는 SYSTEM_CONFIG 에서 KEY_NAME='DATA_KR_API_KEY_YHS' 로 조회
CREATE OR REPLACE PROCEDURE P_CONTENTIMAGE_API_UPSERT
IS
    V_REQ          UTL_HTTP.req;
    V_RESP         UTL_HTTP.resp;
    V_BUFFER       VARCHAR2(10000);
    V_RESPONSE     CLOB;
    V_URL          VARCHAR2(4000);

    V_PAGE_NO      NUMBER;
    V_NUM_OF_ROWS  NUMBER := 100;
    V_TOTAL_COUNT  NUMBER := 0;
    V_MAX_PAGE     NUMBER;

    V_API_KEY        VARCHAR2(200);
    V_APIID          VARCHAR2(100);
    V_RETRY_CNT      NUMBER;
    V_MAX_RETRIES    NUMBER := 3;
    V_SUCCESS        BOOLEAN;
    V_QUOTA_EXCEEDED BOOLEAN := FALSE;
BEGIN
    BEGIN
        SELECT KEY_VALUE INTO V_API_KEY
        FROM SYSTEM_CONFIG
        WHERE KEY_NAME = 'DATA_KR_API_KEY_YHS';
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            DBMS_OUTPUT.PUT_LINE('[에러] API 인증키를 SYSTEM_CONFIG 에서 찾을 수 없습니다.');
            RETURN;
    END;

    UTL_HTTP.set_transfer_timeout(15);

    FOR con IN (SELECT APIID FROM CONTENT ORDER BY CONTENTID) LOOP

        IF V_QUOTA_EXCEEDED THEN
            DBMS_OUTPUT.PUT_LINE('[안내] 할당량 초과로 프로시저 조기 종료합니다.');
            EXIT;
        END IF;

        V_APIID    := con.APIID;
        V_PAGE_NO  := 1;
        V_MAX_PAGE := 1;

        BEGIN
            WHILE V_PAGE_NO <= V_MAX_PAGE LOOP

                V_URL := 'http://apis.data.go.kr/B551011/KorService2/detailImage2'
                    || '?numOfRows='  || V_NUM_OF_ROWS
                    || '&pageNo='     || V_PAGE_NO
                    || '&MobileOS=WEB'
                    || '&MobileApp=TravelMate'
                    || '&_type=json'
                    || '&contentId='  || V_APIID
                    || '&serviceKey=' || V_API_KEY;

                V_RETRY_CNT := 0;
                V_SUCCESS   := FALSE;

                WHILE NOT V_SUCCESS AND V_RETRY_CNT <= V_MAX_RETRIES LOOP
                    BEGIN
                        V_BUFFER := NULL;
                        IF DBMS_LOB.istemporary(V_RESPONSE) = 1 THEN
                            DBMS_LOB.freetemporary(V_RESPONSE);
                        END IF;
                        DBMS_LOB.createtemporary(V_RESPONSE, TRUE);

                        V_REQ := UTL_HTTP.begin_request(V_URL);
                        UTL_HTTP.SET_HEADER(V_REQ, 'Content-Type', 'application/json; charset=UTF-8');
                        UTL_HTTP.SET_BODY_CHARSET(V_REQ, 'UTF-8');
                        V_RESP := UTL_HTTP.get_response(V_REQ);
                        UTL_HTTP.SET_BODY_CHARSET(V_RESP, 'UTF-8');

                        IF V_RESP.status_code <> 200 THEN
                            DBMS_OUTPUT.PUT_LINE('[경고] HTTP ' || V_RESP.status_code
                                                 || ' (APIID: ' || V_APIID || ')');
                            IF V_RESP.status_code = 429 THEN
                                V_RETRY_CNT := V_RETRY_CNT + 1;
                                DBMS_OUTPUT.PUT_LINE('[대기] 429 감지. 3초 후 재시도 ('
                                                     || V_RETRY_CNT || '/' || V_MAX_RETRIES || ')');
                                UTL_HTTP.end_response(V_RESP);
                                DBMS_LOCK.SLEEP(3);
                                CONTINUE;
                            ELSE
                                UTL_HTTP.end_response(V_RESP);
                                RAISE_APPLICATION_ERROR(-20001, 'HTTP ' || V_RESP.status_code);
                            END IF;
                        END IF;

                        BEGIN
                            LOOP
                                UTL_HTTP.read_text(V_RESP, V_BUFFER, 10000);
                                DBMS_LOB.writeappend(V_RESPONSE, LENGTH(V_BUFFER), V_BUFFER);
                            END LOOP;
                        EXCEPTION
                            WHEN UTL_HTTP.end_of_body THEN NULL;
                        END;
                        UTL_HTTP.end_response(V_RESP);

                        IF V_RESPONSE LIKE '%LIMITED_NUMBER_OF_SERVICE_REQUESTS_EXCEEDED%'
                           OR V_RESPONSE LIKE '%quota exceeded%'
                           OR V_RESPONSE LIKE '%returnAuthMsg%' THEN
                            DBMS_OUTPUT.PUT_LINE('[치명] 일일 API 할당량 소모 — 조기 종료');
                            V_QUOTA_EXCEEDED := TRUE;
                            V_SUCCESS := FALSE;
                            EXIT;
                        END IF;

                        V_SUCCESS := TRUE;

                    EXCEPTION
                        WHEN OTHERS THEN
                            BEGIN UTL_HTTP.end_response(V_RESP); EXCEPTION WHEN OTHERS THEN NULL; END;
                            V_RETRY_CNT := V_RETRY_CNT + 1;
                            IF V_RETRY_CNT > V_MAX_RETRIES THEN RAISE; END IF;
                            DBMS_LOCK.SLEEP(2);
                    END;
                END LOOP;

                IF V_QUOTA_EXCEEDED THEN
                    IF DBMS_LOB.istemporary(V_RESPONSE) = 1 THEN DBMS_LOB.freetemporary(V_RESPONSE); END IF;
                    EXIT;
                END IF;

                IF NOT V_SUCCESS THEN
                    DBMS_OUTPUT.PUT_LINE('[실패] APIID ' || V_APIID || ' 3회 재시도 실패, 건너뜁니다.');
                    IF DBMS_LOB.istemporary(V_RESPONSE) = 1 THEN DBMS_LOB.freetemporary(V_RESPONSE); END IF;
                    EXIT;
                END IF;

                BEGIN
                    V_TOTAL_COUNT := TO_NUMBER(JSON_VALUE(V_RESPONSE, '$.response.body.totalCount'));
                EXCEPTION
                    WHEN OTHERS THEN V_TOTAL_COUNT := 0;
                END;

                IF V_PAGE_NO = 1 THEN
                    IF V_TOTAL_COUNT > 0 THEN
                        V_MAX_PAGE := CEIL(V_TOTAL_COUNT / V_NUM_OF_ROWS);
                    ELSE
                        V_MAX_PAGE := 0;
                    END IF;
                    DBMS_OUTPUT.PUT_LINE('== APIID : ' || V_APIID || ' / 총 '
                                         || V_TOTAL_COUNT || '건, ' || V_MAX_PAGE || '페이지');
                END IF;

                IF V_TOTAL_COUNT IS NULL OR V_TOTAL_COUNT <= 0 THEN
                    IF DBMS_LOB.istemporary(V_RESPONSE) = 1 THEN DBMS_LOB.freetemporary(V_RESPONSE); END IF;
                    EXIT;
                END IF;

                IF V_TOTAL_COUNT > 0 THEN
                    FOR r IN (
                        SELECT *
                        FROM JSON_TABLE(V_RESPONSE, '$.response.body.items.item[*]'
                                COLUMNS (
                                    contentid    VARCHAR2(100)  PATH '$.contentid',
                                    originimgurl VARCHAR2(1000) PATH '$.originimgurl',
                                    imgname      VARCHAR2(500)  PATH '$.imgname',
                                    cpyrhtDivCd  VARCHAR2(100)  PATH '$.cpyrhtDivCd',
                                    serialnum    VARCHAR2(500)  PATH '$.serialnum'
                                )
                             )
                    ) LOOP
                        MERGE INTO CONTENTIMAGE t
                        USING DUAL
                        ON (t.APIID = r.contentid AND t.SERIALNUM = r.serialnum)
                        WHEN MATCHED THEN
                            UPDATE SET
                                t.ORIGINIMGURL = r.originimgurl,
                                t.IMGNAME      = r.imgname,
                                t.CPYRHTDIVCD  = r.cpyrhtDivCd
                        WHEN NOT MATCHED THEN
                            INSERT (APIID, ORIGINIMGURL, IMGNAME, CPYRHTDIVCD, SERIALNUM)
                            VALUES (r.contentid, r.originimgurl, r.imgname, r.cpyrhtDivCd, r.serialnum);
                    END LOOP;
                END IF;

                COMMIT;
                DBMS_OUTPUT.PUT_LINE('APIID [' || V_APIID || '] '
                                     || V_PAGE_NO || '/' || V_MAX_PAGE || ' 완료');

                IF DBMS_LOB.istemporary(V_RESPONSE) = 1 THEN DBMS_LOB.freetemporary(V_RESPONSE); END IF;
                V_PAGE_NO := V_PAGE_NO + 1;
                DBMS_LOCK.SLEEP(0.3);

            END LOOP;

        EXCEPTION
            WHEN OTHERS THEN
                ROLLBACK;
                DBMS_OUTPUT.PUT_LINE('[오류] APIID ' || V_APIID || ': ' || SQLERRM);
                IF DBMS_LOB.istemporary(V_RESPONSE) = 1 THEN DBMS_LOB.freetemporary(V_RESPONSE); END IF;
        END;

        IF V_QUOTA_EXCEEDED THEN EXIT; END IF;
        DBMS_LOCK.SLEEP(0.3);

    END LOOP;

    DBMS_OUTPUT.PUT_LINE('=== P_CONTENTIMAGE_API_UPSERT 완료 ===');

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        IF DBMS_LOB.istemporary(V_RESPONSE) = 1 THEN DBMS_LOB.freetemporary(V_RESPONSE); END IF;
END P_CONTENTIMAGE_API_UPSERT;
/


/*==========================================
  [6] 초기 데이터 (없을 경우에만 삽입)
==========================================*/

-- SYSTEM_CONFIG: API 키 등록
-- ※ KEY_VALUE 에 실제 API 키 값을 입력하세요
MERGE INTO SYSTEM_CONFIG T
USING (
    SELECT 'DATA_KR_API_KEY_YHS' AS K, 'YOUR_API_KEY_HERE' AS V, '한국관광공사 API 키 (YHS)' AS D FROM DUAL UNION ALL
    SELECT 'DATA_KR_API_KEY_JSB',      'YOUR_API_KEY_HERE',       '한국관광공사 API 키 (JSB)'  FROM DUAL
) S ON (T.KEY_NAME = S.K)
WHEN NOT MATCHED THEN INSERT (KEY_NAME, KEY_VALUE, DESCRIPTION) VALUES (S.K, S.V, S.D);

-- 컨텐츠 카테고리
MERGE INTO CONTENTCATEGORY T
USING (
    SELECT '12' AS ID, '관광지'       AS NM FROM DUAL UNION ALL
    SELECT '14',       '문화시설'             FROM DUAL UNION ALL
    SELECT '15',       '축제공연행사'          FROM DUAL UNION ALL
    SELECT '25',       '여행코스'             FROM DUAL UNION ALL
    SELECT '28',       '레포츠'               FROM DUAL UNION ALL
    SELECT '32',       '숙박'                 FROM DUAL UNION ALL
    SELECT '38',       '쇼핑'                 FROM DUAL UNION ALL
    SELECT '39',       '음식점'               FROM DUAL
) S ON (T.CONTENTTYPEID = S.ID)
WHEN NOT MATCHED THEN INSERT (CONTENTTYPEID, CONTENTDIV) VALUES (S.ID, S.NM);

-- 일정 이력 액션 타입
MERGE INTO ACTION_TYPE T
USING (
    SELECT 'Act001' AS CD, '생성' AS NM FROM DUAL UNION ALL
    SELECT 'Act002',       '수정'        FROM DUAL UNION ALL
    SELECT 'Act003',       '삭제'        FROM DUAL
) S ON (T.ACTION_TYPE_CD = S.CD)
WHEN MATCHED    THEN UPDATE SET T.ACTION_TYPE_NM = S.NM
WHEN NOT MATCHED THEN INSERT (ACTION_TYPE_CD, ACTION_TYPE_NM) VALUES (S.CD, S.NM);

-- 잘못된 대문자 액션 코드 정리
DELETE FROM ACTION_TYPE
 WHERE ACTION_TYPE_CD IN ('ACT001', 'ACT002', 'ACT003')
   AND NOT EXISTS (
       SELECT 1 FROM TRAVEL_ITINERARY_HIST
        WHERE ACTION_TYPE_CD = ACTION_TYPE.ACTION_TYPE_CD
   );

-- 비용 카테고리
MERGE INTO ITINERARY_EXPENSE_TYPE T
USING (
    SELECT 'EXT001' AS CD, '숙박'      AS NM FROM DUAL UNION ALL
    SELECT 'EXT002',       '교통'              FROM DUAL UNION ALL
    SELECT 'EXT003',       '식비'              FROM DUAL UNION ALL
    SELECT 'EXT004',       '관광/체험'         FROM DUAL UNION ALL
    SELECT 'EXT005',       '쇼핑'              FROM DUAL UNION ALL
    SELECT 'EXT006',       '기타'              FROM DUAL
) S ON (T.EXPENSE_TYPE_CD = S.CD)
WHEN MATCHED    THEN UPDATE SET T.EXPENSE_TYPE_NM = S.NM
WHEN NOT MATCHED THEN INSERT (EXPENSE_TYPE_CD, EXPENSE_TYPE_NM) VALUES (S.CD, S.NM);

-- 미참조 구코드 정리
DELETE FROM ITINERARY_EXPENSE_TYPE
 WHERE EXPENSE_TYPE_CD NOT LIKE 'EXT%'
   AND NOT EXISTS (
       SELECT 1 FROM ITINERARY_EXPENSE
        WHERE ITINERARY_EXPENSE_TYPE = ITINERARY_EXPENSE_TYPE.EXPENSE_TYPE_CD
   );

-- FAQ 카테고리
MERGE INTO FAQ_TYPE T
USING (
    SELECT 'FT001' AS CD, '회원/계정'    AS NM FROM DUAL UNION ALL
    SELECT 'FT002',       '여행계획'             FROM DUAL UNION ALL
    SELECT 'FT003',       '서비스 이용'           FROM DUAL UNION ALL
    SELECT 'FT004',       '기타'                 FROM DUAL
) S ON (T.FAQ_TYPE_CD = S.CD)
WHEN NOT MATCHED THEN INSERT (FAQ_TYPE_CD, FAQ_TYPE_NM) VALUES (S.CD, S.NM);

-- QNA 카테고리
MERGE INTO QNA_TYPE T
USING (
    SELECT 'QT001' AS CD, '회원/계정'    AS NM FROM DUAL UNION ALL
    SELECT 'QT002',       '여행계획'             FROM DUAL UNION ALL
    SELECT 'QT003',       '서비스 이용'           FROM DUAL UNION ALL
    SELECT 'QT004',       '기타'                 FROM DUAL
) S ON (T.QNA_TYPE_CD = S.CD)
WHEN NOT MATCHED THEN INSERT (QNA_TYPE_CD, QNA_TYPE_NM) VALUES (S.CD, S.NM);

-- 여행 테마
MERGE INTO TRAVEL_THEME T
USING (
    SELECT 'TH001' AS CD, '힐링'        AS NM FROM DUAL UNION ALL
    SELECT 'TH002',       '관광/문화'           FROM DUAL UNION ALL
    SELECT 'TH003',       '맛집 투어'           FROM DUAL UNION ALL
    SELECT 'TH004',       '액티비티'            FROM DUAL UNION ALL
    SELECT 'TH005',       '가족 여행'           FROM DUAL UNION ALL
    SELECT 'TH006',       '자연/힐링'           FROM DUAL
) S ON (T.TRAVEL_THEME_CD = S.CD)
WHEN NOT MATCHED THEN INSERT (TRAVEL_THEME_CD, TRAVEL_THEME_NM) VALUES (S.CD, S.NM);

-- 리뷰 신고 타입 (VARCHAR2 코드)
MERGE INTO REVIEW_REPORT_TYPE T
USING (
    SELECT 'RT001' AS CD, '욕설/비하'  AS NM FROM DUAL UNION ALL
    SELECT 'RT002',       '스팸/광고'          FROM DUAL UNION ALL
    SELECT 'RT003',       '허위 정보'          FROM DUAL UNION ALL
    SELECT 'RT004',       '기타'               FROM DUAL
) S ON (T.REPORT_TYPE_CD = S.CD)
WHEN NOT MATCHED THEN INSERT (REPORT_TYPE_CD, REPORT_TYPE_NM) VALUES (S.CD, S.NM);

-- 초기 관리자 계정 (없을 경우에만: admin / admin1234)
MERGE INTO ADMIN_ACCOUNT T
USING (SELECT 'admin' AS ID FROM DUAL) S
ON (T.ID = S.ID)
WHEN NOT MATCHED THEN
    INSERT (ADMIN_NO, ID, PW)
    VALUES (ADMIN_ACCOUNT_SEQ.NEXTVAL, 'admin', CRYPTPACK.ENCRYPT('admin1234', 'YOUR_CRYPTO_KEY_HERE'));  -- application.yml 의 crypto.key 와 동일하게 입력

COMMIT;
