/*===============================================
    travle_content.sql
    - 컨텐츠 기능 개발 중 사용한 테스트 쿼리 모음
    - 실행 순서 없음 (참고용)
===============================================*/

-- 컨텐츠 카테고리 조회
SELECT CONTENTTYPEID, CONTENTDIV
FROM CONTENTCATEGORY
;


-- 갯수 조회
SELECT COUNT(*)
FROM CONTENT;

-- 목록 (즐겨찾기는 추후에 추가/MEMBER_NO 필요)
SELECT
    A.CONTENTID
    ,TITLE, ADDR1
    , A.CONTENTTYPEID, B.CONTENTDIV
    , FIRSTIMAGE
    , NVL(C.REVIEW_COUNT, 0) AS REVIEW_COUNT
    , NVL(AVG_RATING, 0) AS AVG_RATING
    , D.EVENTSTARTDATE AS EVENTSTARTDATE
    , D.EVENTENDDATE AS EVENTENDDATE
FROM CONTENT A
JOIN CONTENTCATEGORY B ON A.CONTENTTYPEID = B.CONTENTTYPEID
LEFT JOIN (
    SELECT CONTENTID, COUNT(*) AS REVIEW_COUNT, AVG(NVL(RATING, 0)) AS AVG_RATING
    FROM CONTENT_REVIEW
    GROUP BY CONTENTID
) C ON A.CONTENTID = C.CONTENTID
LEFT JOIN CONTENTEVENT D ON A.CONTENTID = D.CONTENTID
ORDER BY A.MODIFIEDTIME DESC
OFFSET 0 ROWS FETCH FIRST 10 ROWS ONLY
;

-- 컨텐츠 카테고리 필터
SELECT
    A.CONTENTID
    ,TITLE, ADDR1    , A.CONTENTTYPEID, B.CONTENTDIV
    , FIRSTIMAGE    , NVL(C.REVIEW_COUNT, 0) AS REVIEW_COUNT
    , NVL(AVG_RATING, 0) AS AVG_RATING
    , D.EVENTSTARTDATE AS EVENTSTARTDATE
    , D.EVENTENDDATE AS EVENTENDDATE
FROM CONTENT A
JOIN CONTENTCATEGORY B ON A.CONTENTTYPEID = B.CONTENTTYPEID
LEFT JOIN (
    SELECT CONTENTID, COUNT(*) AS REVIEW_COUNT, AVG(NVL(RATING, 0)) AS AVG_RATING
    FROM CONTENT_REVIEW
    GROUP BY CONTENTID
) C ON A.CONTENTID = C.CONTENTID
LEFT JOIN CONTENTEVENT D ON A.CONTENTID = D.CONTENTID
WHERE A.CONTENTTYPEID = '15'
  AND INSTR(TITLE, '강남') > 0
ORDER BY A.MODIFIEDTIME DESC
OFFSET 0 ROWS FETCH FIRST 10 ROWS ONLY
;

-- 행사 컨텐츠 검색
-- 컨텐츠 카테고리 필터
SELECT
    A.CONTENTID
    , D.EVENTSTARTDATE AS EVENTSTARTDATE
    ,TITLE, ADDR1    , A.CONTENTTYPEID, B.CONTENTDIV
    , FIRSTIMAGE    , NVL(C.REVIEW_COUNT, 0) AS REVIEW_COUNT
    , NVL(AVG_RATING, 0) AS AVG_RATING
    , D.EVENTENDDATE AS EVENTENDDATE
FROM CONTENT A
JOIN CONTENTCATEGORY B ON A.CONTENTTYPEID = B.CONTENTTYPEID
LEFT JOIN (
    SELECT CONTENTID, COUNT(*) AS REVIEW_COUNT, AVG(NVL(RATING, 0)) AS AVG_RATING
    FROM CONTENT_REVIEW
    GROUP BY CONTENTID
) C ON A.CONTENTID = C.CONTENTID
LEFT JOIN CONTENTEVENT D ON A.CONTENTID = D.CONTENTID
WHERE A.CONTENTTYPEID = '15'
  AND TO_DATE(EVENTSTARTDATE, 'YYYY-MM-DD') >= TO_DATE('20251212', 'YYYY-MM-DD')
ORDER BY A.MODIFIEDTIME DESC
;


DESC CONTENT;
/*
CONTENTID     NOT NULL NUMBER         
TITLE                  VARCHAR2(500)  
ADDR1                  VARCHAR2(1000) 
ADDR2                  VARCHAR2(1000) 
CONTENTTYPEID          VARCHAR2(1000) 
CREATEDTIME            VARCHAR2(14)   
MAPX                   NUMBER(20,15)  
MAPY                   NUMBER(20,15)  
MODIFIEDTIME           VARCHAR2(14)   
APIID                  VARCHAR2(100)  
FIRSTIMAGE             VARCHAR2(1000) 
FIRSTIMAGE2            VARCHAR2(1000)
*/

-- 컨텐츠 상세
SELECT
E.CONTENTID ,
    A.CONTENTID
    ,TITLE, ADDR1, ADDR2
    , A.CONTENTTYPEID, B.CONTENTDIV
    , MAPX, MAPY
    , FIRSTIMAGE, FIRSTIMAGE2
    , NVL(C.REVIEW_COUNT, 0) AS REVIEW_COUNT
    , NVL(AVG_RATING, 0) AS AVG_RATING
    , D.EVENTSTARTDATE AS EVENTSTARTDATE
    , D.EVENTENDDATE AS EVENTENDDATE
    , CASE 
        WHEN E.CONTENTID IS NOT NULL THEN 'Y'
        ELSE 'N'END AS BOOKMARK
FROM CONTENT A
JOIN CONTENTCATEGORY B ON A.CONTENTTYPEID = B.CONTENTTYPEID
LEFT JOIN (
    SELECT CONTENTID, COUNT(*) AS REVIEW_COUNT, AVG(NVL(RATING, 0)) AS AVG_RATING
    FROM CONTENT_REVIEW
    GROUP BY CONTENTID
) C ON A.CONTENTID = C.CONTENTID
LEFT JOIN CONTENTEVENT D ON A.CONTENTID = D.CONTENTID
LEFT JOIN MEMBER_BOOKMARK E
     ON A.CONTENTID = E.CONTENTID AND E.MEMBER_NO = 4
WHERE A.CONTENTID = 829
;

--○ 즐겨찾기 등록
INSERT INTO MEMBER_BOOKMARK(BOOKMARK_NO, MEMBER_NO, CONTENTID)
VALUES(MEMBER_BOOKMARK_SEQ.NEXTVAL, 4, 829);

--○ 즐겨찾기 삭제
DELETE MEMBER_BOOKMARK
WHERE MEMBER_NO = 4 AND CONTENTID = '829';

--○ 리뷰 조회
SELECT CONTENT_REVIEW_NO, CONTENTID
, A.MEMBER_NO
, B.NICKNAME
, REVIEW_COMMENT
, RATING
, A.CREATE_DT
FROM CONTENT_REVIEW A
JOIN MEMBER_ACTIVE B ON A.MEMBER_NO = B.MEMBER_NO
WHERE CONTENTID = 829
ORDER BY A.CREATE_DT DESC
OFFSET 0 ROWS FETCH FIRST 10 ROWS ONLY;

--○ 리뷰 등록
INSERT INTO CONTENT_REVIEW(CONTENT_REVIEW_NO, MEMBER_NO, CONTENTID, REVIEW_COMMENT, RATING)
VALUES(CONTENT_REVIEW_SEQ, 4, 829, 'ㅎㅎ', 5);